In [1]:
# array only holds same type of objects.
import numpy as np

In [2]:
my_lst = [1,2,3,4,5,6]

In [3]:
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
# multi-nested array
# 2d array

my_lst1 = [1,2,3,4,5,6,7]
my_lst2 = [2,55,6,7,6,4,3]
my_lst3 = [22,6,7,4,2,3,5]

arr_2d = np.array([my_lst1,my_lst2,my_lst3])

In [6]:
print(arr_2d)

[[ 1  2  3  4  5  6  7]
 [ 2 55  6  7  6  4  3]
 [22  6  7  4  2  3  5]]


In [7]:
type(arr_2d)

numpy.ndarray

In [8]:
# indexing

my_lst = [1,2,3,4,5,6]
arr = np.array(my_lst)

In [9]:
arr[3]

4

In [10]:
arr[5]

6

In [11]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2, 55,  6,  7,  6,  4,  3],
       [22,  6,  7,  4,  2,  3,  5]])

In [12]:
arr_2d[0,1]

2

In [13]:
arr_2d[1,5]

4

In [14]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [15]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr_3d[0,:,0:2]

array([[1, 2],
       [4, 5]])

In [17]:
arr_3d[1 , : ,1:]

array([[ 8,  9],
       [11, 12]])

In [18]:
arr_2d[1:,2:4]

array([[6, 7],
       [7, 4]])

In [19]:
arr_2d[0:2,5:]

array([[6, 7],
       [4, 3]])

In [20]:
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
arr[2] = 100

In [22]:
arr

array([  1,   2, 100,   4,   5,   6])

In [23]:
### Some conditions very useful in Exploratory Data Analysis 

val = 2
arr[arr>3]

array([100,   4,   5,   6])

In [24]:
# create array and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
import numpy as np
arr1 = np.arange(0,12).reshape(3,4)


In [27]:
newarr = arr1.reshape(1,3,4)

In [28]:
arr2 = np.arange(0,10).reshape(5,2)

In [29]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (3,4) (5,2) 

In [ ]:
arr1+arr2

In [ ]:
arr1/arr2

In [ ]:
arr1%arr2

In [ ]:
np.ones((5,4),dtype = int)

In [ ]:
# random distribution
# rand gives values between 0 and 1
np.random.rand(4,4)

In [ ]:
# randn gives values of standrardization values like -1 to 1 or -2 or 2
np.random.randn(4,4)

In [ ]:
np.random.randint(0,100,20).reshape(5,4)

In [ ]:
np.random.random_sample((1,10)).reshape(5,2)

In [36]:
a = np.arange(1000)

In [37]:
a.itemsize

4

In [38]:
a.size

1000

In [39]:
b = np.array([1,2,3,4])

In [40]:
b.ndim

1

In [41]:
c = np.array([[1,2],[3,4],[5,6]])

In [42]:
c.ndim

2

In [43]:
a = np.array([1,2,3,4], dtype=float)

In [44]:
a

array([1., 2., 3., 4.])

In [45]:
a.size

4

In [47]:
c.shape

(3, 2)

In [49]:
a = np.zeros((3,4))

In [50]:
np.arange(1,5)

array([1, 2, 3, 4])

In [52]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [53]:
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [54]:
a = np.arange(12).reshape(3,4)

In [55]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a[1,1:3]

array([5, 6])

In [58]:
a[1,:]

array([4, 5, 6, 7])

In [59]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [61]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [67]:
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

In [68]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])